version: '3.5'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13.2
    volumes:
      - $POSTGRES_MIGRATION_PATH:/docker-entrypoint-initdb.d
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - $ADMINER_PORT:8080
    depends_on:
      - postgres
    networks:
      - data

networks:
  data:

